name: IBS Monitor

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:


permissions:
  contents: read


jobs:

  monitor:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - run: |
          pip install web3==6.20.1 requests


      - name: Run monitor

        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

        run:

          python monitor.py
